# Generated by Django 5.1.1 on 2024-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomers_app', '0002_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rutaIMG',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
